language: node_js
node_js:
  - "17"
services:
  - mysql
env:
  - NODE_ENV=test
before_install:
  - mysql -e "CREATE USER 'law'@'%' IDENTIFIED WITH mysql_native_password BY 'password';"
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'law'@'%';"
  - mysql -e 'CREATE DATABASE IF NOT EXISTS law_memo_test default character set utf8mb4 collate utf8mb4_unicode_ci;'
  - npm install sequelize-cli -g
  - export JWT_SECRET_KEY=legalDictionary
before_script:
  - sequelize db:migrate            