language: node_js
node_js:
  - "18"
services:
  - mysql
env:
  - NODE_ENV=travis
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS law_memo_workspace_test default character set utf8mb4 collate utf8mb4_unicode_ci;'
  - npm install sequelize-cli -g
  - export JWT_SECRET_KEY=legalDictionary
before_script:
  - sequelize db:migrate            