language: node_js
node_js:
    - "17"
services:
    - mysql
env:
    - NODE_ENV=test
install:
    - mysql -e 'ALTER USER 'root'@'localhost' IDENTIFIED BY 'MyN3wP4ssw0rd';'
    - mysql -e 'CREATE DATABASE IF NOT EXISTS law_memo_test default character set utf8mb4 collate utf8mb4_unicode_ci;'
    - npm install
    - npm install sequelize-cli -g
    - npm install mocha -g
    - export JWT_SECRET_KEY=legalDictionary
script:
    - sequelize db:migrate             