language: node_js
node_js:
  - "17"
services:
  - mysql
env:
  - NODE_ENV=travis
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS law_memo_workplace default character set utf8mb4 collate utf8mb4_unicode_ci;'
  - npm install sequelize-cli -g
  - export JWT_SECRET_KEY=legalDictionary
before_script:
  - sequelize db:migrate            
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "AKIATDV5XJTZYGW4NISZ"
  secret_access_key:
    secure: "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"
  region: "ap-southeast-1"
  app: "law-memo"
  env: "legal-Dictionary"
  bucket_name: "elasticbeanstalk-ap-southeast-1-214072511731"