version: '3'
services:
  dev:
    build: .
    container_name: lawmemo_dev
    ports:
      - '3000:3000'
    env_file: .env
    command: npm run start
    volumes:
      - .:/app 
    depends_on: mysql 
  mysql: 
    image: mysql:8
    container_name: mysql_dev
    environment:
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - DB_HOST
    command: ["mysqld", "--character-set-service=utf8mb4", "--collate=urf8mb4-unicide-ci"]
    restart: always
    volumes: 
      - db:/var/lib/mysql
volumes:
  db:        
