version: 2.1
orbs:
  node: circleci/node@4.7
jobs:
  build_and_test: 
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          version: '18.13'
          pkg-manager: npm
      - run:
         command: NODE_ENV=test
         name: env
      - run:
         command: mysql -e 'CREATE DATABASE IF NOT EXISTS forum_test default character set utf8mb4 collate utf8mb4_unicode_ci;'
         name: create database
      - run:
         command: npm install sequelize-cli -g
         name: install sequelize cli
      - run:
         command: export JWT_SECRET_KEY=legalDictionary
         name: export jwt secret
      - run:
         command: sequelize db:migrate
         name: create table
      - run:
         command: npm run test
         name: run test
workflows:
  CICD:
    jobs:
      - build_and_test
      


         