version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  db:
    docker:   
      - image: circleci/mysql:5.7 
    steps:
      - checkout
      - run:
         command: mysql -h 127.0.0.1 -u root -p password -e 'CREATE DATABASE IF NOT EXISTS law_memo_test;'
         name: create database  
  build: 
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: 
          command: export JWT_SECRET_KEY=legalDictionary
      - run:
         command: set NODE_ENV=test
         name: env  
      - run:
         command: npm install sequelize-cli -g
         name: install sequelize cli
      - run:
         command: sequelize db:migrate
         name: create table
      - run:
         command: npm run test
         name: run test
          
workflows:
  CICD:
    jobs:
      - db
      - build
      


         