version: 2.1
orbs:
  node: circleci/node:latest
  mysql: circleci/mysql:latest
jobs:
  db:
     executor: mysql/default
     steps:
      - checkout
  build: 
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      steps:
      - checkout
      - run:
         command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
         name: Waiting for MySQL to be ready
      -run: 
          command: export JWT_SECRET_KEY=legalDictionary
      - run:
         command: set NODE_ENV=test
         name: env
      - run:
         command: sudo apt-get install default-mysql-client
         name: install mysql-client   
      - run:
         command: mysql -h 127.0.0.1 -u root -p password law_memo_test  -e 'CREATE DATABASE IF NOT EXISTS law_memo_test default character set utf8mb4 collate utf8mb4_unicode_ci;'
         name: create database
      - run:
         command: npm install sequelize-cli -g
         name: install sequelize cli
      - run:
         command: sequelize db:migrate
         name: create table
      - run:
         command: npm run test
         name: run test
          
workflows:
  CICD:
    jobs:
      - db
      - build
      


         